routes/web.php
<?php

Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::get('user/profile/{id}', 'Admin\UsersController@userProfile')->name('user.profile');
    Route::post('user/profile', 'Admin\UsersController@saveProfile')->name('user.Saveprofile');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::resource('farmer', 'Admin\farmerController');
    Route::resource('company', 'Admin\CompanyController');
    Route::delete('company_mass_destroy', 'Admin\CompanyController@massDestroy')->name('company.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::delete('fpo_mass_destroy', 'Admin\fpoController@massDestroy')->name('fpo.mass_destroy');
    Route::resource('customer', 'Admin\CustomerController');
    Route::delete('customer_mass_destroy', 'Admin\CustomerController@massDestroy')->name('customer.mass_destroy');
    Route::resource('crop', 'Admin\CropController');
    Route::resource('fig', 'Admin\FigController');
    Route::get('fig/addfarmer/{id}', 'Admin\FigController@addfarmer')->name('fig.addfarmer');
    Route::post('fig/savefarmer', 'Admin\FigController@savefarmer')->name('fig.savefarmer');
    Route::get('lrp/{id}', 'Admin\FigController@addlrp')->name('fig.addlrp');
    Route::post('savelrp', 'Admin\FigController@savelrp')->name('fig.savelrp');
    Route::get('otherdoc/{id}', 'Admin\fpoController@otherdoc')->name('fpo.fpoController');
    Route::get('fpo/comapny/{id}', 'Admin\fpoController@comapny')->name('fpo.upload');
    Route::get('fpo/fig/{id}', 'Admin\fpoController@fig')->name('fpo.fig');
});

resources/views/partials/menu.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">

        <ul class="nav">
            <li class="nav-item">
                <a href="{{ route("admin.home") }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-tachometer-alt">

                    </i>
                    {{ trans('global.dashboard') }}
                </a>
            </li>
            @can('users_manage')
            <li class="nav-item nav-dropdown">
                <a class="nav-link  nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-users nav-icon">

                    </i>
                    {{ trans('cruds.userManagement.title') }}
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                            <i class="fa-fw fas fa-unlock-alt nav-icon">

                            </i>
                            {{ trans('cruds.permission.title') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                            <i class="fa-fw fas fa-briefcase nav-icon">

                            </i>
                            {{ trans('cruds.role.title') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                            <i class="fa-fw fas fa-user nav-icon">

                            </i>
                            {{ trans('cruds.user.title') }}
                        </a>
                    </li>

                </ul>
            <li class="nav-item">
                <a href="{{ route("admin.company.index") }}" class="nav-link {{ request()->is('admin/company') || request()->is('admin/company/*') ? 'active' : '' }}">
                    <i class="fa-fw fas fa-user nav-icon">

                    </i>
                    {{ trans('cruds.company.title') }}
                </a>
            </li>
            </li>
            @endcan
            @canany(['users_manage','company_manage'])
            <li class="nav-item">
                <a href="{{ route('admin.customer.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-key">

                    </i>
                    Employee
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('admin.fpo.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-key">

                    </i>
                    FPO Details
                </a>
            </li>

            @endcanany


            @canany(['users_manage','employee_manage','company_manage'])
            <li class="nav-item">
                <a href="{{ route('admin.farmer.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-key">

                    </i>
                    Farmer Details
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('admin.fig.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-key">

                    </i>
                    FIG Group
                </a>
            </li>
            @endcanany
            <li class="nav-item">
                <a href="{{ route('auth.change_password') }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-key">

                    </i>
                    Change password
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                    <i class="nav-icon fas fa-fw fa-sign-out-alt">

                    </i>
                    {{ trans('global.logout') }}
                </a>
            </li>



        </ul>

    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>