routes/web.php
<?php

Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::get('user/profile/{id}', 'Admin\UsersController@userProfile')->name('user.profile');
    Route::post('user/profile', 'Admin\UsersController@saveProfile')->name('user.Saveprofile');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::resource('farmer', 'Admin\farmerController');
    Route::resource('company', 'Admin\CompanyController');
    Route::delete('company_mass_destroy', 'Admin\CompanyController@massDestroy')->name('company.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::delete('fpo_mass_destroy', 'Admin\fpoController@massDestroy')->name('fpo.mass_destroy');
    Route::resource('customer', 'Admin\CustomerController');
    Route::delete('customer_mass_destroy', 'Admin\CustomerController@massDestroy')->name('customer.mass_destroy');
    Route::resource('crop', 'Admin\CropController');
    Route::resource('fig', 'Admin\FigController');
    Route::get('fig/addfarmer/{id}', 'Admin\FigController@addfarmer')->name('fig.addfarmer');
    Route::post('fig/savefarmer', 'Admin\FigController@savefarmer')->name('fig.savefarmer');
    Route::get('lrp/{id}', 'Admin\FigController@addlrp')->name('fig.addlrp');
    Route::post('savelrp', 'Admin\FigController@savelrp')->name('fig.savelrp');
    Route::get('otherdoc/{id}', 'Admin\fpoController@otherdoc')->name('fpo.fpoController');
    Route::get('fpo/comapny/{id}', 'Admin\fpoController@comapny')->name('fpo.upload');
    Route::get('fpo/fig/{id}', 'Admin\fpoController@fig')->name('fpo.fig');
});

app/Crop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Crop extends Model
{
    protected $fillable = ['farmer_id','season_id', 'crop_name', 'area', 'total_production',
    'average_yield','direct','through_intermediaries','total'];
    
    public function farmer()
    {
        return $this->belongsTo(farmer::class);
    }
    public function Season()
    {
        return $this->belongsTo(Season::class);
    }
}

app/Http/Controllers/Admin/CropController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Crop;
use App\farmer;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\StoreCropRequest;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Season;
use Illuminate\Support\Facades\Auth;

class CropController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('employee_manage')) {
            return abort(401);
        }

        $crops = Crop::with('farmer')->get();
        dd( $crops); exit;
        return view('admin.crop.index', compact('crops'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCropRequest $request)
    {
     
        if (! Gate::any(['employee_manage','company_manage','users_manage'])) {
            return abort(401);
        }
        $user = Crop::create($request->all());
        $farmer = farmer::where('id',$request->farmer_id)->first();
        $farmers = farmer::with('fpo')->get();
        //$crops = Crop::with('Season','farmer')->where('farmer_id',$farmer->id)->get();
      
        toastr()->success('Crop has been saved successfully!');
        return redirect()->route('admin.farmer.edit',compact('farmers','farmer'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::any(['employee_manage','company_manage','users_manage'])) {
            return abort(401);
        }
        $cropData = Season::all();
        return view('admin.crop.create',compact('id','cropData'));
    }
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Crop $crop)
    {   
      
        if (! Gate::any(['employee_manage','company_manage','users_manage'])) {
            return abort(401);
        }

        $crop->delete();
        if (Gate::allows('users_manage')) {
            $farmers = farmer::with('fpo','employee')
            ->get();

        }else{
            $farmers = farmer::with('fpo','employee')
            ->where('employee_id',Auth::id())
            ->get();
        }
    
        toastr()->success('crop has been deleted successfully!');
        return view('admin.farmer.index', compact('farmers'));
    }
}

resources/views/admin/crop/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.crop.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.crop.store") }}" method="POST" id="corpForm" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('season') ? 'has-error' : '' }}">
                <label for="season_id">season*</label>
                <select name="season_id" id="season_id" class="form-control">
                    <option selected disabled>Please select season</option>
                    @foreach ($cropData as $key => $cropDatas)
                    <option value="{{$cropDatas->id }}" {{ !empty(old('season_id')) && old('season_id') == $cropDatas->id
                            ? 'selected="selected"'
                            : ((!empty($crop) && !empty($crop->season_id)) && $crop->season_id == $cropDatas->id
                                ? 'selected="selected"'
                                : "")
                        }}>{{ $cropDatas->name }}</option>
                    @endforeach

                </select>

                @if($errors->has('season_id'))
                <em class="invalid-feedback">
                    {{ $errors->first('season_id') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('crop_name') ? 'has-error' : '' }}">
                <label for="crop_name">{{ trans('cruds.crop.fields.crop_name') }}*</label>
                <input type="hidden" name="farmer_id" value="{{$id}}">
                <input type="text" id="crop_name" name="crop_name" class="form-control" value="{{ old('crop_name', isset($crop) ? $crop->crop_name : '') }}" required>
                @if($errors->has('crop_name'))
                <em class="invalid-feedback">
                    {{ $errors->first('crop_name') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.crop_name_helper') }}
                </p>
            </div>


            <div class="form-group {{ $errors->has('area') ? 'has-error' : '' }}">
                <label for="area">Area (Hectare)</label>
                <input type="text" id="area" name="area" class="form-control" value="{{ old('area', isset($crop) ? $crop->area : '') }}" required>
                @if($errors->has('area'))
                <em class="invalid-feedback">
                    {{ $errors->first('area') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.area_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('total_production') ? 'has-error' : '' }}">
                <label for="total_production"> Production (Kg)</label>
                <input type="text" id="total_production" name="total_production" class="form-control" value="{{ old('total_production', isset($crop) ? $crop->total_production : '') }}" required>
                @if($errors->has('total_production'))
                <em class="invalid-feedback">
                    {{ $errors->first('total_production') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.total_production_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('average_yield') ? 'has-error' : '' }}">
                <label for="average_yield">Average Yield (Kg/Hectare)</label>
                <input type="text" id="average_yield" name="average_yield" class="form-control" value="{{ old('average_yield', isset($crop) ? $crop->average_yield : '') }}" required>
                @if($errors->has('average_yield'))
                <em class="invalid-feedback">
                    {{ $errors->first('average_yield') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.average_yield_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('direct') ? 'has-error' : '' }}">
                <label for="direct">{{ trans('cruds.crop.fields.direct') }}</label>
                <input type="text" id="direct" name="direct" class="form-control" value="{{ old('direct', isset($crop) ? $crop->direct : '') }}" required>
                @if($errors->has('direct'))
                <em class="invalid-feedback">
                    {{ $errors->first('direct') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.direct_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('through_intermediaries') ? 'has-error' : '' }}">
                <label for="through_intermediaries">{{ trans('cruds.crop.fields.through_intermediaries') }}</label>
                <input type="text" id="through_intermediaries" name="through_intermediaries" class="form-control" value="{{ old('through_intermediaries', isset($crop) ? $crop->through_intermediaries : '') }}" required>
                @if($errors->has('through_intermediaries'))
                <em class="invalid-feedback">
                    {{ $errors->first('through_intermediaries') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.through_intermediaries_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('total') ? 'has-error' : '' }}">
                <label for="total">{{ trans('cruds.crop.fields.total') }}</label>
                <input type="text" id="total" name="total" class="form-control" value="{{ old('total', isset($crop) ? $crop->total : '') }}" required>
                @if($errors->has('total'))
                <em class="invalid-feedback">
                    {{ $errors->first('total') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.crop.fields.total_helper') }}
                </p>
            </div>

            <div style="float:left; margin-right:15px;">
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
            <div style="float:left;">
                <a class="btn btn-primary" href="{{ route('admin.farmer.edit', $id) }}">Back</a>
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/crop/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.user.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.users.update", [$user->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.user.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($user) ? $user->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('cruds.user.fields.email') }}*</label>
                <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($user) ? $user->email : '') }}" required>
                @if($errors->has('email'))
                    <em class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.email_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">{{ trans('cruds.user.fields.password') }}</label>
                <input type="password" id="password" name="password" class="form-control">
                @if($errors->has('password'))
                    <em class="invalid-feedback">
                        {{ $errors->first('password') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.password_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('roles') ? 'has-error' : '' }}">
                <label for="roles">{{ trans('cruds.user.fields.roles') }}*
                    <span class="btn btn-info btn-xs select-all">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all">{{ trans('global.deselect_all') }}</span></label>
                <select name="roles[]" id="roles" class="form-control select2" multiple="multiple" required>
                    @foreach($roles as $id => $roles)
                        <option value="{{ $id }}" {{ (in_array($id, old('roles', [])) || isset($user) && $user->roles()->pluck('name', 'id')->contains($id)) ? 'selected' : '' }}>{{ $roles }}</option>
                    @endforeach
                </select>
                @if($errors->has('roles'))
                    <em class="invalid-feedback">
                        {{ $errors->first('roles') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/crop/index.blade.php
@extends('layouts.admin')
@section('content')
@can('employee_manage')
<div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
        <a class="btn btn-success" href="{{ route("admin.crop.create") }}">
            {{ trans('global.add') }} {{ trans('cruds.user.title_singular') }}
        </a>
    </div>
</div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.crop.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>

                        <th class="hide">
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.roles') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $key => $user)
                    <tr data-entry-id="{{ $user->id }}">
                        <td class="hide">
                        </td>

                        <td>
                            {{ $user->id ?? '' }}
                        </td>
                        <td>
                            {{ $user->name ?? '' }}
                        </td>
                        <td>
                            {{ $user->email ?? '' }}
                        </td>
                        <td>
                            @foreach($user->roles()->pluck('name') as $role)
                            <span class="badge badge-info">{{ $role }}</span>
                            @endforeach
                        </td>
                        <td>
                            <!-- <a class="btn btn-xs btn-primary" href="{{ route('admin.users.show', $user->id) }}">
                                    {{ trans('global.view') }}
                                </a> -->

                            <a class="btn btn-xs btn-info" href="{{ route('admin.users.edit', $user->id) }}">
                                {{ trans('global.edit') }}
                            </a>

                            <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                            </form>

                        </td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function() {
        let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
        @can('users_manage')
        let deleteButtonTrans = '{{ trans('
        global.datatables.delete ') }}'
        let deleteButton = {
            text: deleteButtonTrans,
            url: "{{ route('admin.users.mass_destroy') }}",
            className: 'btn-danger',
            action: function(e, dt, node, config) {
                var ids = $.map(dt.rows({
                    selected: true
                }).nodes(), function(entry) {
                    return $(entry).data('entry-id')
                });

                if (ids.length === 0) {
                    alert('{{ trans('
                        global.datatables.zero_selected ') }}')

                    return
                }

                if (confirm('{{ trans('
                        global.areYouSure ') }}')) {
                    $.ajax({
                            headers: {
                                'x-csrf-token': _token
                            },
                            method: 'POST',
                            url: config.url,
                            data: {
                                ids: ids,
                                _method: 'DELETE'
                            }
                        })
                        .done(function() {
                            location.reload()
                        })
                }
            }
        }
        dtButtons.push(deleteButton)
        @endcan

        $.extend(true, $.fn.dataTable.defaults, {
            order: [
                [1, 'desc']
            ],
            pageLength: 10,
        });
        $('.datatable-User:not(.ajaxTable)').DataTable({
            buttons: dtButtons
        })
        $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
            $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust();
        });
    })
</script>
@endsection

resources/views/admin/crop/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.user.title') }}
    </div>

    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <td>
                            {{ $user->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <td>
                            {{ $user->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <td>
                            {{ $user->email }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Roles
                        </th>
                        <td>
                            @foreach($user->roles()->pluck('name') as $role)
                                <span class="label label-info label-many">{{ $role }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection