routes/web.php
<?php

Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::get('user/profile/{id}', 'Admin\UsersController@userProfile')->name('user.profile');
    Route::post('user/profile', 'Admin\UsersController@saveProfile')->name('user.Saveprofile');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::resource('farmer', 'Admin\farmerController');
    Route::resource('company', 'Admin\CompanyController');
    Route::delete('company_mass_destroy', 'Admin\CompanyController@massDestroy')->name('company.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::delete('fpo_mass_destroy', 'Admin\fpoController@massDestroy')->name('fpo.mass_destroy');
    Route::resource('customer', 'Admin\CustomerController');
    Route::delete('customer_mass_destroy', 'Admin\CustomerController@massDestroy')->name('customer.mass_destroy');
    Route::resource('crop', 'Admin\CropController');
    Route::resource('fig', 'Admin\FigController');
    Route::get('fig/addfarmer/{id}', 'Admin\FigController@addfarmer')->name('fig.addfarmer');
    Route::post('fig/savefarmer', 'Admin\FigController@savefarmer')->name('fig.savefarmer');
    Route::get('lrp/{id}', 'Admin\FigController@addlrp')->name('fig.addlrp');
    Route::post('savelrp', 'Admin\FigController@savelrp')->name('fig.savelrp');
    Route::get('otherdoc/{id}', 'Admin\fpoController@otherdoc')->name('fpo.fpoController');
    Route::get('fpo/comapny/{id}', 'Admin\fpoController@comapny')->name('fpo.upload');
    Route::get('fpo/fig/{id}', 'Admin\fpoController@fig')->name('fpo.fig');
});

app/Fig.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fig extends Model
{

    protected $fillable = ['fpo_id', 'name', 'created_by'];

    public function fpo()
    {
        return $this->belongsTo(fpo::class);
    }

    public function fig_farmer(){
        return $this->hasMany(fig_farmer::class);
    }
    public function farmer(){
        return $this->hasOne(farmer::class);
    }
}

app/Http/Controllers/Admin/FigController.php
<?php

namespace App\Http\Controllers\Admin;

use App\company;
use App\farmer;
use Illuminate\Support\Facades\Gate;
use App\Fig;
use App\Customer;
use App\fig_farmer;
use App\fpo;
use App\Http\Requests\Admin\StoreFigRequest;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Validation\Validator as ValidationValidator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator as FacadesValidator;
use Illuminate\Validation\Validator;

class FigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!Gate::any(['employee_manage', 'company_manage', 'users_manage'])) {
            return abort(401);
        }

        if (Gate::any(['company_manage'])) {

            $company = company::where('user_id', Auth::id())->first();

            $fpos = fpo::where('company_id', $company->id)
                ->get()->pluck('id')->implode(',');
            $fposId = explode(',', $fpos);
            $figs = Fig::with('fpo', 'fig_farmer', 'farmer')
                ->whereIn('fpo_id', $fposId)
                ->get();



            return view('admin.fig.index', compact('figs'));
        }
        if (Gate::any(['employee_manage'])) {

            $customer = customer::where('user_id', Auth::id())->first();

            $fpos = fpo::where('company_id', $customer->company_id)
                ->where('assign_emp', $customer->id)->get()->pluck('id')->implode(',');
            $fposId = explode(',', $fpos);

            $figs = Fig::with('fpo', 'fig_farmer', 'farmer')
                ->whereIn('fpo_id', $fposId)
                ->get();


            return view('admin.fig.index', compact('figs'));
        }

        $figs = Fig::with('fpo', 'fig_farmer', 'farmer')->get();
        //  dd( $figs );
        return view('admin.fig.index', compact('figs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Gate::any(['employee_manage', 'company_manage', 'users_manage'])) {
            return abort(401);
        }
        if (Gate::allows('users_manage')) {
            $fpos = fpo::get();
            return view('admin.fig.create', compact('fpos'));
        }

        if (Gate::allows('company_manage')) {

            $company = company::where('user_id', Auth::id())->first();

            $fpos = fpo::where('company_id', $company->id)->get();
            return view('admin.fig.create', compact('fpos'));
        }

        if (Gate::allows('employee_manage')) {


            $customer = Customer::where('user_id', Auth::id())->first();

            $fpos = fpo::where('assign_emp', $customer->id)->get();
            return view('admin.fig.create', compact('fpos'));
        }

        $fpos = fpo::all();
        return view('admin.fig.create', compact('fpos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFigRequest $request)
    {
        if (!Gate::any(['employee_manage', 'company_manage', 'users_manage'])) {
            return abort(401);
        }
        $user = Fig::create($request->all());

        toastr()->success('Fig has been saved successfully!');
        return redirect()->route('admin.fig.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(fig $fig)
    {
        if (!Gate::any(['employee_manage', 'company_manage', 'users_manage'])) {
            return abort(401);
        }
        if (Gate::allows('users_manage')) {
            $fpos = fpo::get();
            return view('admin.fig.edit', compact('fpos', 'fig'));
        }

        if (Gate::allows('company_manage')) {

            $company = company::where('user_id', Auth::id())->first();

            $fpos = fpo::where('company_id', $company->id)->get();
            return view('admin.fig.edit', compact('fpos', 'fig'));
        }

        if (Gate::allows('employee_manage')) {


            $customer = Customer::where('user_id', Auth::id())->first();

            $fpos = fpo::where('company_id', $customer->company_id)->get();
            return view('admin.fig.edit', compact('fpos', 'fig'));
        }

        $fpos = fpo::all();
        return view('admin.fig.edit', compact('fpos', 'fig'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreFigRequest $request, fig $fig)
    {
        if (!Gate::any(['employee_manage', 'company_manage', 'users_manage'])) {
            return abort(401);
        }

        $fig->update($request->all());

        toastr()->success('Fig has been updated successfully!');
        return redirect()->route('admin.fig.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(fig $fig)
    {
        if (!Gate::any(['employee_manage', 'company_manage', 'users_manage'])) {
            return abort(401);
        }

        $getFig = fig_farmer::where('fig_id', $fig->id)->get();

        foreach ($getFig as $deleteFarmer) {
            $userUpdate['is_assign'] = 0;
            $userUpdate['fig_id'] = 0;
            farmer::where('id', $deleteFarmer->farmer_id)->update($userUpdate);
        }


        foreach ($getFig as $delete) {
            $delete->delete();
        }
        $fig->delete();
        toastr()->success('Fig has been deleted successfully!');
        return redirect()->route('admin.fig.index');
    }

    public function addfarmer($id)
    {

        $fig = fig::with('fpo')
            ->where('id', $id)->first();
        $figFarmer = fig_farmer::get()->pluck('farmer_id');

        if (Gate::any(['employee_manage'])) {
            $customer = customer::where('user_id', Auth::id())->first();
            $fpos = fpo::where('id', $fig->fpo_id)->get()->pluck('id')->implode(',');
            $fposId = explode(',', $fpos);

            $farmers = farmer::with('fig_farmer')
                ->whereIn('fpo_id', $fposId)
                ->Where('fig_id', 0)
                ->orWhere('fig_id', $id)
                ->get();
        }
        if (Gate::any(['users_manage'])) {

            $farmers = farmer::with('fig_farmer')
                ->where('fpo_id', $fig->fpo_id)
                ->Where('fig_id', 0)
                ->orWhere('fig_id', $id)
                ->get();
        }

        if (Gate::any(['company_manage'])) {

            $farmers = farmer::with('fig_farmer')
                ->where('fpo_id', $fig->fpo_id)
                ->Where('fig_id', 0)
                ->orWhere('fig_id', $id)
                ->get();
        }

        return view('admin.fig.addfarmer', compact('fig', 'farmers'));
    }
    public function savefarmer(Request $request)
    {

        $this->validate($request, [
            'duallistbox_demo1' => 'required'
        ]);

        if ($request['fig_id']) {
            $figFarmer = fig_farmer::where('fig_id', $request['fig_id'])
                ->where('customer_id', Auth::id())
                ->get();

            foreach ($figFarmer as $delete) {
                $userUpdate['is_assign'] = 0;
                $userUpdate['fig_id'] = 0;
                farmer::where('id', $delete->farmer_id)->update($userUpdate);
                fig_farmer::find($delete->id)->delete();
            }
        }

        $figs = Fig::with('fpo')->get();
        foreach ($request->duallistbox_demo1 as $val) {

            $userUpdate['is_assign'] = 1;
            $userUpdate['fig_id'] = $request['fig_id'];

            farmer::where('id', $val)->update($userUpdate);

            $farmer = fig_farmer::create(
                [
                    'fpo_id' => $request['fpo_id'],
                    'fig_id' => $request['fig_id'],
                    'farmer_id' => $val,
                    'customer_id' => Auth::id(),
                ]
            );
        }

        toastr()->success('Farmers has been deleted successfully!');
        return redirect('/admin/fig');
        //return view('admin.fig.index',compact('figs'));


    }


    public function addlrp($id)
    {


        $figFarmers = fig_farmer::with('farmer')
            ->where('fig_id', $id)->get();

        return view('admin.fig.showlrp', compact('figFarmers'));
    }
    public function savelrp(Request $request)
    {

        $this->validate($request, [
            'selectFarmer' => 'required'
        ]);
        $a = fig_farmer::where('id', $request['selectFarmer'])->first();

        $b = fig_farmer::where('fig_id', $a->fig_id)->get();
        foreach ($b as $c) {
            $fig_farmer = fig_farmer::find($c->id);
            $fig_farmer->lrp = 0;
            $fig_farmer->save();
        }

        $fig_farmer = fig_farmer::find($request->selectFarmer);
        $fig_farmer->lrp = 1;
        $fig_farmer->save();
        $figs = Fig::with('fpo')->get();
        toastr()->success('Farmers has been selected successfully!');

resources/views/admin/fig/addfarmer.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.fig.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.fig.savefarmer") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('fpo_id') ? 'has-error' : '' }}">
                <label for="fpo_id">Fpo : </label>
                <input type="hidden" name="fpo_id" id="fpo_id" value="{{$fig->fpo->id}}" readonly>
                <span><b>{{$fig->fpo->fpo_name}}</b></span>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">Group name : </label>
                <input type="hidden" name="fig_id" id="fig_id" value="{{$fig->id}}" readonly>
                <span><b>{{$fig->name}}</b></span>
            </div>

            <div class="form-group {{ $errors->has('fpo_id') ? 'has-error' : '' }}">
                <label for="fpo_id">Farmer</label>

                <select multiple="multiple" size="10" id="duallistbox_demo1" name="duallistbox_demo1[]" required>
                    <option selected disabled>Please select Farmer</option>

                    @foreach ($farmers as $key => $farmer)
                    <option value="{{$farmer->id}}" <?php if ($farmer->fig_farmer != null) {
                                                        if (
                                                            $farmer->id == $farmer->fig_farmer->farmer_id &&
                                                            $farmer->fig_farmer->fig_id == $fig->id
                                                        ) { ?> selected <?php } ?> <?php
                                                                                } ?>>{{$farmer->farmer_name}} - {{$farmer->village}}</option>


                    @endforeach
                </select>

                @if($errors->has('fpo_id'))
                <em class="invalid-feedback">
                    {{ $errors->first('fpo_id') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>


            <div style="float:left;margin-right:15px;">
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
            <div style="float:left;">
                <a class="btn btn-primary" href="{{ route('admin.fig.index') }}">Back</a>
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/fig/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.fig.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.fig.store") }}" method="POST" id="figForm" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="created_by" value="{{Auth::id()}}">
            <div class="form-group {{ $errors->has('fpo_id') ? 'has-error' : '' }}">
                <label for="fpo_id">Fpo*</label>
                <select  name="fpo_id" id="fpo_id" class="form-control">
                        <option selected disabled>Please select fpo</option>
                        @foreach ($fpos as $key => $fpo)
                        <option value="{{ $fpo->id }}"
                        {{ !empty(old('fpo_id')) && old('fpo_id') == $value->id
                            ? 'selected="selected"'
                            : ((!empty($farmer) && !empty($farmer->fpo_id)) && $fpo->fpo_id == $fpo->id
                                ? 'selected="selected"'
                                : "")
                        }}>{{ $fpo->fpo_name }}</option>
                    @endforeach

                    </select>
                  
                @if($errors->has('fpo_id'))
                    <em class="invalid-feedback">
                        {{ $errors->first('fpo_id') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.fig.fields.name_group') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($fig) ? $fig->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fig.fields.name_group_helper') }}
                </p>
            </div>
           
            <div style="float:left;margin-right:15px;">
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
            <div style="float:left;">
                <a class="btn btn-primary" href="{{ route('admin.fig.index') }}">Back</a>
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/fig/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.fig.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.fig.update", [$fig->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="hidden" name="created_by" value="{{Auth::id()}}">
            <div class="form-group {{ $errors->has('fpo_id') ? 'has-error' : '' }}">
                <label for="fpo_id">Fpo*</label>
                <select  name="fpo_id" id="fpo_id" class="form-control">
                        <option selected disabled>Please select fpo</option>
                        @foreach ($fpos as $key => $fpo)
                        <option value="{{ $fpo->id }}"
                        {{ !empty(old('fpo_id')) && old('fpo_id') == $value->id
                            ? 'selected="selected"'
                            : ((!empty($fig) && !empty($fig->fpo_id)) && $fig->fpo_id == $fpo->id
                                ? 'selected="selected"'
                                : "")
                        }}>{{ $fpo->fpo_name }}</option>
                    @endforeach

                    </select>
                  
                @if($errors->has('fpo_id'))
                    <em class="invalid-feedback">
                        {{ $errors->first('fpo_id') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>

            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.fig.fields.name_group') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($fig) ? $fig->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fig.fields.name_group_helper') }}
                </p>
            </div>
            <div style="float:left;margin-right:15px;">
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
            <div style="float:left;">
                <a class="btn btn-primary" href="{{ route('admin.fig.index') }}">Back</a>
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/fig/index.blade.php
@extends('layouts.admin')
@section('content')
@canany(['users_manage','employee_manage','company_manage'])
<div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
        <a class="btn btn-success" href="{{ route("admin.fig.create") }}">
            {{ trans('global.add') }} {{ trans('cruds.fig.title_singular') }}
        </a>
    </div>
</div>
@endcanany
<div class="card">
    <div class="card-header">
        {{ trans('cruds.fig.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th class="hide">
                        </th>
                        <th>
                            {{ trans('cruds.fig.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.fig.fields.fpo_id') }}
                        </th>
                        <th>
                            FIG Name
                        </th>
                        <th>
                            LRP Name
                        </th>
                        <th>
                            LRP Mobile
                        </th>

                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($figs as $key => $fig)
                    <tr data-entry-id="{{ $fig->id }}">
                        <td class="hide">
                        </td>
                        <td>
                            {{ $fig->id ?? '' }}
                        </td>
                        <td>
                            {{ $fig->fpo->fpo_name ?? '' }}
                        </td>
                        <td>
                            {{ $fig->name ?? '' }}
                        </td>
                        <td>
                            <?php

                            foreach ($fig->fig_farmer as $val) {
                                if ($val->lrp == 1) {
                                    $farmer = App\farmer::where('id', $val->farmer_id)->first();
                            ?>
                                    {{$farmer->farmer_name ?? ''}}
                                <?php } else { ?>

                            <?php }
                            } ?>
                        </td>
                        <td>
                            <?php
                            foreach ($fig->fig_farmer as $val) {
                                if ($val->lrp == 1) {
                                    $farmer =  App\farmer::where('id', $val->farmer_id)->first();
                            ?>
                                    {{$farmer->contact_no ?? ''}}
                                <?php } else { ?>

                            <?php }
                            } ?>

                        </td>


                        <td>
                            @canany(['users_manage','employee_manage','company_manage'])
                            <a class="btn btn-xs btn-info" href="{{ route('admin.fig.addfarmer', $fig->id) }}">
                                Add Farmers
                            </a>

                            <a class="btn btn-xs btn-info" href="{{ route('admin.fig.addlrp', $fig->id) }}">
                                Add LRP
                            </a>

                            <a class="btn btn-xs btn-info" href="{{ route('admin.fig.edit', $fig->id) }}">
                                {{ trans('global.edit') }}
                            </a>

                            <form action="{{ route('admin.fig.destroy', $fig->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                            </form>
                            @endcanany
                        </td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function() {
        let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
        // @can('users_manage')
        //   let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
        //   let deleteButton = {
        //     text: deleteButtonTrans,
        //     url: "{{ route('admin.users.mass_destroy') }}",
        //     className: 'btn-danger',
        //     action: function (e, dt, node, config) {
        //       var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
        //           return $(entry).data('entry-id')
        //       });

        //       if (ids.length === 0) {
        //         alert('{{ trans('global.datatables.zero_selected') }}')

        //         return
        //       }

        //       if (confirm('{{ trans('global.areYouSure') }}')) {
        //         $.ajax({
        //           headers: {'x-csrf-token': _token},
        //           method: 'POST',
        //           url: config.url,
        //           data: { ids: ids, _method: 'DELETE' }})
        //           .done(function () { location.reload() })
        //       }
        //     }
        //   }
        //   dtButtons.push(deleteButton)
        // @endcan

        $.extend(true, $.fn.dataTable.defaults, {
            order: [
                [1, 'desc']
            ],
            pageLength: 10,
        });
        $('.datatable-User:not(.ajaxTable)').DataTable({
            buttons: dtButtons
        })
        $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
            $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust();
        });
    })
</script>
@endsection

resources/views/admin/fig/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.user.title') }}
    </div>

    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <td>
                            {{ $user->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <td>
                            {{ $user->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <td>
                            {{ $user->email }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Roles
                        </th>
                        <td>
                            @foreach($user->roles()->pluck('name') as $role)
                                <span class="label label-info label-many">{{ $role }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection

resources/views/admin/fig/showlrp.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} Show LRP
    </div>

    <div class="card-body">
        <form action="{{ route("admin.fig.savelrp") }}" method="POST" enctype="multipart/form-data">
            @csrf
         
            <div class="form-group {{ $errors->has('fpo_id') ? 'has-error' : '' }}">
                <label for="fpo_id">Farmer</label>
               
                <select id="selectFarmer"  class="form-control" name="selectFarmer" required>
                <option selected disabled>Please select Farmer</option>
                    
                    @foreach ($figFarmers as $key => $figFarmer)
                    <option value="{{$figFarmer->id}}" <?php if($figFarmer->lrp == 1) { ?> selected <?php } ?>>{{$figFarmer->farmer->farmer_name}}</option>
                    @endforeach
                    </select>
                  
                @if($errors->has('fpo_id'))
                    <em class="invalid-feedback">
                        {{ $errors->first('fpo_id') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>

            <div style="float:left;margin-right:15px;">
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
            <div style="float:left;">
                <a class="btn btn-primary" href="{{ route('admin.fig.index') }}">Back</a>
            </div>
        </form>


    </div>
</div>
@endsection